- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8085/"
        status_code:
          - 200
          - 403
    - name: Check pipeline job state
      community.general.jenkins_job_info:
        name: "pipeline-job"
        user: "admin"
        password: "admin"
        url: "http://127.0.0.1:8085"
        validate_certs: false
      retries: 15
      delay: 30
      register: jenkins_job_info
      until: >
        'jobs' in jenkins_job_info and
        jenkins_job_info.jobs[0]['name'] == 'pipeline-job' and
        'blue' in jenkins_job_info.jobs[0]['color']
