- name: Place job files to Jenkins home directory
  template: src=templates/{{item.template_file}}
    dest={{jenkins_home}}/{{item.job_file}}
    owner=jenkins group=jenkins mode=0644
  with_items: "{{jenkins_jobs}}"
- name: Create Jenkins jobs
  shell: "{{jenkins_cli}} create-job {{item.name}} < {{jenkins_home}}/{{item.job_file}}"
  with_items: "{{jenkins_jobs}}"
  register: job_create_result
  failed_when: (job_create_result.rc != 4) and (job_create_result.rc != 0)
  changed_when: job_create_result.rc == 0
- name: Build Jenkins jobs
  command: "{{jenkins_cli}} build {{item.name}}"
  when: "{{item.build}}"
  with_items: "{{jenkins_jobs}}"
# source:  git@github.com:grawert/ansible-jenkins-ci.git